sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: UgPZC+rpR8q6QphwAHqTROkHqA5XJA7D1ejS1RNZOfw4tahqcxdtl6CKUUuzURfAZVjLvFA1MTcD+XgOt7zjEssMfdG/APwSqzDJP+BOTYzzLcHMyueYWIM5Xsafz2iQzISrdeA7zqk8uJ9WO+CNZQ0WoEMNHu334cJsMoLjpLM+WScJiYLu2+YCsyAIcpE5v1HAnND7dzVh7PNT9AVtUygF26JDypPqUEKvZgDlH/i6KybtfPkcW4RHh2kXoly2q1fN5ue7QqGjr+DQ9Yob38DAL+0Jjs+w1DmPGS7msPy9q5sgf4uRujFX4s2XKF8+TX2OrOCy5CYPqVyfOcrmR9V3YYRUGXs/VnGlcn+10QR6GkqgxWDtjIO/fH6qMoKJHSxxdku6b/7gN3ppzL+snt5g7MDWmvr6BNtT7FI667C29j8FNkVagWItf74ckzCTueH/qrxN57hBwCTBj/XPf1VHfq+q6teriRF/VG8hn49FAI9HzL21LlnxoJWt9eDolBe8IhzrR2RAAN/Bq1ibknmtGw9/TAI2hxGNcm81A04Rh5PZQi6InWw8cuDkoLtiuSKzTIW5C/dq0ITa8EjBEXvBchTCrpF/yq33X8oLTJRg/T/uTAukfVwReXLoRA/NIEF+rMKHsXNEWyeUfUrUQhFn8qVEvUkOMA/HzX1Jxqg=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Tales-of-Terror-and-Mystery_537
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy